/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-fixed": "#ffddb5",
        "surface-tint": "#835400",
        "primary": "#835400",
        "on-primary-fixed": "#2a1800",
        "on-tertiary-container": "#4f493a",
        "on-secondary-fixed-variant": "#474746",
        "on-primary-container": "#674100",
        "on-secondary-container": "#636262",
        "surface-container-high": "#eae8e4",
        "tertiary-fixed-dim": "#cfc5b3",
        "outline-variant": "#d7c3ae",
        "primary-container": "#f9a825",
        "surface-container-highest": "#e4e2de",
        "primary-fixed-dim": "#ffb957",
        "surface-container": "#efeeea",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed-variant": "#4c4638",
        "surface-variant": "#e4e2de",
        "on-surface": "#1b1c1a",
        "secondary": "#5f5e5e",
        "on-primary": "#ffffff",
        "background": "#fbf9f5",
        "secondary-fixed": "#e5e2e1",
        "on-error-container": "#93000a",
        "error": "#ba1a1a",
        "on-primary-fixed-variant": "#643f00",
        "inverse-primary": "#ffb957",
        "tertiary": "#655e4e",
        "on-tertiary": "#ffffff",
        "on-error": "#ffffff",
        "secondary-fixed-dim": "#c8c6c5",
        "tertiary-fixed": "#ece1ce",
        "on-secondary": "#ffffff",
        "surface-container-low": "#f5f3ef",
        "surface": "#fbf9f5",
        "outline": "#857462",
        "surface-bright": "#fbf9f5",
        "on-secondary-fixed": "#1c1b1b",
        "on-tertiary-fixed": "#201b0f",
        "tertiary-container": "#c1b8a5",
        "secondary-container": "#e2dfde",
        "inverse-surface": "#30312e",
        "on-background": "#1b1c1a",
        "inverse-on-surface": "#f2f0ed",
        "surface-dim": "#dbdad6",
        "error-container": "#ffdad6",
        "on-surface-variant": "#524434"
      },
      fontFamily: {
        "headline": ["var(--font-epilogue)", "sans-serif"],
        "body": ["var(--font-jakarta)", "sans-serif"],
        "accent": ["var(--font-aurore)", "cursive"],
        "display": ["var(--font-montserrat)", "sans-serif"]
      },
    },
  },
  plugins: [require("daisyui"), require("@tailwindcss/forms")],
};